### ISSUE TITLE
Initializing game || Don't know which mods have issues with Pipes mod

### ISSUE THREAD

**Issue by msgninja** [vini2003/Pipes#1]
Disable this mods will launch the game perfect. Enable this mod will cause crash and won't launch at all. Don't know which mod having issues with Pipes mod.

[crash-2019-08-14_02.18.43-client.txt](https://github.com/vini2003/Pipes/files/3500058/crash-2019-08-14_02.18.43-client.txt)

> ---- Minecraft Crash Report ----
> // Shall we play a game?
> 
> Time: 8/14/19 2:18 AM
> Description: Initializing game
> 
> org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
> 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:179)
> 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:142)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at net.minecraft.class_310.method_1503(class_310.java:586)
> 	at net.minecraft.class_310.method_1514(class_310.java:394)
> 	at net.minecraft.client.main.Main.main(Main.java:155)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
> Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [pipes.mixin.json:MixinInGameHud] from phase [DEFAULT] in config [pipes.mixin.json] FAILED during APPLY
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
> 	... 21 more
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @Inject annotation on handler$onRender$zbk000 could not find any targets matching 'render' in the target class net.minecraft.class_329. Using refmap Pipes-refmap.json
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:421)
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:172)
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:159)
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:151)
> 	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:44)
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:472)
> 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1180)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:930)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:318)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:281)
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
> 	... 21 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Client thread
> Stacktrace:
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
> 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:179)
> 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:142)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at net.minecraft.class_310.method_1503(class_310.java:586)
> 
> -- Initialization --
> Details:
> Stacktrace:
> 	at net.minecraft.class_310.method_1514(class_310.java:394)
> 	at net.minecraft.client.main.Main.main(Main.java:155)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.14.4
> 	Minecraft Version ID: 1.14.4
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_144, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 1170912248 bytes (1116 MB) / 3306160128 bytes (3153 MB) up to 7478968320 bytes (7132 MB)
> 	CPUs: 4
> 	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8024m
> 	Fabric Mods: 
> 		abusedlib: AbusedLib 1.3.0
> 		alwaysdroploot: Always Drop Loot 3.6.0+mc1.14.4
> 		animalnet: MrMarnic's AnimalNet v1.14.4 Fabric b3
> 		appleskin: AppleSkin 1.0.7
> 		autoconfig1: Auto Config v1 1.2.0+mc1.14.4
> 		blue_endless_jankson: jankson 1.1.0
> 		cardinal-components-base: Cardinal Components API 2.0.1-SNAPSHOT
> 		cardinal-components-block: Cardinal Components API 2.0.1-SNAPSHOT
> 		cardinal-components-item: Cardinal Components API 2.0.1-SNAPSHOT
> 		cardinalenergy: Cardinal Energy 1.3.0
> 		cloth: Cloth Events 0.4.0
> 		cloth-config: Cloth Config 0.2.4+build.17
> 		cloth-config2: Cloth Config v2 0.5.2
> 		com_typesafe_config: config 1.3.1
> 		cotton-energy: Cotton Energy 1.5.0+1.14.3
> 		cotton-resources: Cotton Resources 1.4.1+1.14.4
> 		cursedchests: CursedChests 2.3.23
> 		de_javagl_obj: obj 0.3.0
> 		easyexcavate: Easy Excavate 1.5.1
> 		energies: Energies 1.14.4-1.0.14
> 		extrabows: Extra Bows v1.14.4 Fabric b2
> 		fabric: Fabric API 0.3.1+build.208
> 		fabric-api-base: fabric-api-base 0.1.0+59147463
> 		fabric-biomes-v1: fabric-biomes-v1 0.1.0+896c7fbb42
> 		fabric-commands-v0: fabric-commands-v0 0.1.1+b494ebeb42
> 		fabric-containers-v0: fabric-containers-v0 0.1.2+b494ebeb42
> 		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+b494ebeb42
> 		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.1+9f55aa7042
> 		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.1+9f55aa7042
> 		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.1+eff46b3d42
> 		fabric-furnaces: Fabric Furnaces 1.1.7
> 		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
> 		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c42
> 		fabric-language-kotlin: Fabric Language Kotlin 1.3.40+build.1
> 		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+b494ebeb42
> 		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+ab421b9c42
> 		fabric-models-v0: fabric-models-v0 0.1.0+5914746342
> 		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+b494ebeb42
> 		fabric-networking-v0: fabric-networking-v0 0.1.3+9f55aa7042
> 		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+9b03381f42
> 		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+9b03381f42
> 		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.1+9b03381f42
> 		fabric-renderer-indigo: fabric-renderer-indigo 0.1.10+f0fe03ff42
> 		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+b494ebeb42
> 		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.1+39442fc242
> 		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e42
> 		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.2+232e294c42
> 		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+b494ebeb42
> 		fabric-textures-v0: fabric-textures-v0 0.1.4+b494ebeb42
> 		fabricloader: Fabric Loader 0.4.8+build.159
> 		generators: Generators 1.14.4-1.1.2
> 		iamverysmart: I Am Very Smart 1.5.0+mc1.14.4
> 		jankson: Jankson 1.0.0+j1.1.2
> 		leveluphp: Level Up HP 4.4.0+mc1.14.4
> 		libblockattributes: LibBlockAttributes 0.4.9
> 		libblockattributes_core: LibBlockAttributes (Core) 0.4.9
> 		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.4.9
> 		libblockattributes_items: LibBlockAttributes (Items) 0.4.9
> 		libcd: LibCapableData 1.3.1+1.14.4
> 		libgui: LibGui 1.2.2
> 		materialisation: Materialisation 0.5.4
> 		modmenu: Mod Menu 1.7.7+build.116
> 		modnametooltip: Mod Name Tool Tips 1.1.0
> 		orderly: Orderly 1.0.1+build.7
> 		org_jetbrains_annotations: annotations 16.0.3
> 		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.40
> 		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.40
> 		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.40
> 		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.2.2
> 		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.2.2
> 		org_spongepowered_configurate-core: configurate-core 3.6
> 		org_spongepowered_configurate-hocon: configurate-hocon 3.6
> 		pipes: Pipes 1.14.4-0.0.1
> 		protos: Protos 1.14.4-1.0.2
> 		reborncore: Reborn Core 4.0.9.128
> 		refinedmachinery: Refined Machinery 1.2.1
> 		resourcemelons: Resource Melons 2.0.0
> 		roughlyenoughitems: Roughly Enough Items 2.9.7+build.145
> 		silk: Silk API 1.2.4-43
> 		simpleteleporters: Simple Teleporters 2.2.0
> 		stockpile: Stockpile 1.0.9+1.14.4
> 		techreborn: Tech Reborn 3.0.7.138
> 		theoneprobe: The One Probe 1.4.29.beta
> 		trapexpansion: Trap Expansion 1.2.0
> 		vanilla-hammers: Vanilla Hammers 1.6.1
> 		vivatech: Vivatech 1.0.0-alpha.14+1.14.4
> 		voxelmap: VoxelMap 1.9.13
> 	Launched Version: MultiMC5
> 	LWJGL: 3.2.2 build 10
> 	OpenGL: Radeon (TM) RX 480 Graphics GL version 4.6.13547 Compatibility Profile Context 25.20.15031.1000, ATI Technologies Inc.
> 	GL Caps: Using GL 1.3 multitexturing.
> Using GL 1.3 texture combiners.
> Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
> Shaders are available because OpenGL 2.1 is supported.
> VBOs are available because OpenGL 1.5 is supported.
> 
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fabric'
> 	Type: Client (map_client.txt)
> 	Resource Packs: 
> 	Current Language: English (US)
> 	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz

**Comment by vini2003** [comment]
That's weird. My Mixin is trying to target a class different than the one I specified.
Will investigate further.

EDIT: think I know why.

**Comment by vini2003** [comment]
Fixed; issue was not remapping Mixin method on build. It worked in the dev. environment, but not outside of it.
