### ISSUE TITLE
Inserting to a furnace or Fabric furnace

### ISSUE THREAD

**Issue by Snowfalldevice** [vini2003/Pipes#2]
Using the new item pipes, it was sending the same items into both the top and bottom slots of a furnace.

**Comment by vini2003** [comment]
In my single-player testing before pushing the latest version to CurseForge this was working fine, interesting. I'm essentially rewriting the whole thing right now so I'll get to this soon.

**Comment by vini2003** [comment]
Interesting!

I pushed the wrong build to CurseForge!

I'll be uploading a fixed build ASAP.
